---
deployment:
  tasks:
    - export DEPLOYPATH=/home/basicsof/localseodigest/wp-content/themes/localseodigest/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -r 404.php $DEPLOYPATH
    - /bin/cp -r footer.php $DEPLOYPATH
    - /bin/cp -r front-page.php $DEPLOYPATH
    - /bin/cp -r functions.php $DEPLOYPATH
    - /bin/cp -r header.php $DEPLOYPATH
    - /bin/cp -r index.php $DEPLOYPATH
    - /bin/cp -r page-about.php $DEPLOYPATH
    - /bin/cp -r page-contact.php $DEPLOYPATH
    - /bin/cp -r page-glossary.php $DEPLOYPATH
    - /bin/cp -r page-resources.php $DEPLOYPATH
    - /bin/cp -r page.php $DEPLOYPATH
    - /bin/cp -r search.php $DEPLOYPATH
    - /bin/cp -r single.php $DEPLOYPATH
    - /bin/cp -r style.css $DEPLOYPATH
    - /bin/cp -r js $DEPLOYPATH